### PR TITLE
feat: NFT mint unguardedly

### PR DESCRIPTION
**Pull request by danielwpz**
The existing `mint` function requires that the caller must be the owner.

However this is just an assumption of how the users might use this contract, in fact there might be (and already has) some cases in which other users can also mint NFTs as long as some requirements are met.

The existing `mint` function is kept to make this contract backwards compatible. I added one `internal_mint_unguarded` function for derived contracts to bypass the owner restriction.

### CODE REVIEW

**Review by willemneal — APPROVED** [review]
Thank you! This a great first step in making the minting process more customizable and standardizable.

**Review by austinabell — APPROVED** [review]
Awesome, was planning on doing exactly this tomorrow. Thanks for the contribution

**Comment by austinabell** [comment]
cc @mikedotexe since you're most aware of NFT standard and how it will be changing.

As for CI failing, `cargo fmt` is failing and the NFT example needs to be rebuilt (see `CONTRIBUTING.md` for info on this).

If you'd like I can fix this if I have permissions to push to this PR branch

**Comment by ilblackdragon** [comment]
I suggest we use `internal_` as indicator of everything that doesn't do any checks. This is how it is in Fungible Token.
So we don't need extra "_unguaded" then.

I would then remove `mint` completely. It doesn't belong in the library anyway.

**Comment by austinabell** [comment]
> I would then remove `mint` completely. It doesn't belong in the library anyway.

Can just mark the function as deprecated in this PR, and this will be removed later (avoid hard breaking change)

**Review by mikedotexe — APPROVED** [review]

**Comment by danielwpz** [comment]
@ilblackdragon @mikedotexe updated

**Pull request merged**
