### PR TITLE
chore: bump versions to 4.0.0-pre.2

### PR DESCRIPTION
**Pull request by austinabell**
bumped versions for next release, published already https://crates.io/crates/near-sdk/versions

### CODE REVIEW

**Comment by mikedotexe** [comment]
What's the reason for changing to GPL? I probably missed this in discussions somewhere.

**Comment by austinabell** [comment]
> What's the reason for changing to GPL? I probably missed this in discussions somewhere.

I assume someone just forgot to update the license in `Cargo.toml` for the macros crate, the license everywhere else and `LICENSE` file in the repo is gpl3

**Review by mikedotexe — APPROVED** [review]
As per discussions elsewhere, I believe dual license of MIT and Apache 2 would be ideal. Approving with the knowledge that this will be discussed and reached

**Review by ChaoticTempest — APPROVED** [review]
👍

**Review by chefsale — APPROVED** [review]
Licences look fine to me.

**Pull request merged**
