### PR TITLE
chore: updates near-* dependencies to 0.24.0

### PR DESCRIPTION
**Pull request by akorchyn**
near-workspaces should be updated later. It's not a blocker as it's used in tests and it has cyclic dependency :)

cc @race-of-sloths

### CODE REVIEW

**Comment by race-of-sloths** [comment]
@akorchyn Thank you for your contribution! Your pull request is now a part of the [Race of Sloths](https://race-of-sloths.com)!
We are launching a survey "Who is faster? You vs SpaceX"

[<picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://badge.race-of-sloths.com/akorchyn?type=bot&theme=dark">
    <source media="(prefers-color-scheme: light)" srcset="https://badge.race-of-sloths.com/akorchyn?type=bot&theme=light">
    Shows profile picture for the author of the PR
</picture>](https://race-of-sloths.com/profile/akorchyn)


<details><summary>Current status: <i>waiting for scoring</i></summary>

We're waiting for maintainer to score this pull request with `@race-of-sloths score [0,1,2,3,5,8,13]` command. Alternatively, autoscoring [1,2] will be applied for this pull request

</details><details><summary>What is the Race of Sloths</summary>
<p>
Race of Sloths is a friendly competition where you can participate in challenges and compete with other open-source contributors within your normal workflow

For contributors:

- Tag @race-of-sloths inside your pull requests
- Wait for the maintainer to review and score your pull request
- Check out your position in the [Leaderboard](https://race-of-sloths.com/leaderboard)
- Keep weekly and monthly streaks to reach higher positions
- Boast your contributions with a dynamic picture of your [Profile](https://race-of-sloths.com/profile/akorchyn)

For maintainers:
- Score pull requests that participate in the Race of Sloths
- Engage contributors with fair scoring and fast responses so they keep their streaks
- Promote the Race to the point where the Race starts promoting you
- Grow the community of your contributors

Feel free to check [our website](https://race-of-sloths.com) for additional details!
</p>
</details> 

<details>
<summary>Bot commands</summary>

- For contributors
  - **Include a PR:** `@race-of-sloths include` to enter the Race with your PR
- For maintainers:
  - **Invite contributor** `@race-of-sloths invite` to invite the contributor to participate in a race or include it, if it's already a runner.
  - **Assign points:** `@race-of-sloths score [1/2/3/5/8/13]` to award points based on your assessment.
  - **Reject this PR:** `@race-of-sloths exclude` to send this PR back to the drawing board.
  - **Exclude repo:** `@race-of-sloths pause` to stop bot activity in this repo until `@race-of-sloths unpause` command is called

</details>

**Comment by dj8yfo** [comment]
@ruseinov `insert_and_remove` fails in storage_performance_tests.rs (a few reruns). What's a possible fix?

**Comment by ruseinov** [comment]
> @ruseinov `insert_and_remove` fails in storage_performance_tests.rs (a few reruns). What's a possible fix?

Run locally and adjust the number if iterations for each collection.
In this case it consumes less gas than expected, it's not a bad thing. There was enough slack given to avoid those errors, but if there is a significant deviation - this will fail with an error.

**Comment by akorchyn** [comment]
I have updated amount of iterations, let's see, but anyways, we should a bit on hold this PR, as windows is part of testing, and it's broken now in 0.24 release :(

See details: https://near.zulipchat.com/#narrow/stream/295558-core/topic/windows.20compilation.20issue.20on.202.2E0.2E0/near/459477738

**Comment by ruseinov** [comment]
> I have updated amount of iterations, let's see, but anyways, we should a bit on hold this PR, as windows is part of testing, and it's broken now in 0.24 release :(
> 
> See details: https://near.zulipchat.com/#narrow/stream/295558-core/topic/windows.20compilation.20issue.20on.202.2E0.2E0/near/459477738

There is another collection that is failing now. I would suggest running those tests locally first an making sure they are well above the lower range on your machine. Then it's likely to pass in the CI.

Yeah, it seems broken indeed.

**Review by frol — APPROVED** [review]
Did we get a free 5-10% improvement in runtime performance by just upgrading the dependencies? Nice

**Comment by akorchyn** [comment]
+1, but also I think that you had improved overall performance, but it was still in range and this PR just reached the threshold

**Comment by akorchyn** [comment]
+1, but also I think that you had improve overall performance, but it was still in range and this PR just reached the threshold

**Review by ruseinov — APPROVED** [review]

**Comment by race-of-sloths** [comment]
🥁  __Score it!__

@frol @ruseinov, please score the PR with `@race-of-sloths score [1/2/3/5/8/13]`. The contributor deserves it.
If no scoring is provided within 24 hours, this PR will be scored as 2 🦥

**Comment by frol** [comment]
@race-of-sloths score 5

**Comment by ruseinov** [comment]
@race-of-sloths score 5

**Pull request merged**
