### PR TITLE
bug report(near-sdk-sim): profile_data() fails

### PR DESCRIPTION
**Pull request by chadoh**
TODO:

- [x] wait for #327 to get merged, retarget this PR at `master`

---

adding `res.profile_data()` to this test causes the following error:

    profile_data: ------------------------------
    Total gas: 0
    thread 'with_macros::simulate_transfer_call_promise_panics_for_a_full_refund' panicked at 'denominator == 0', /Users/chadoh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.3.2/src/lib.rs:128:13
    stack backtrace:
       0: std::panicking::begin_panic
                 at /Users/chadoh/.rustup/toolchains/stable-2020-10-08-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/panicking.rs:497
       1: num_rational::Ratio<T>::reduce
                 at /Users/chadoh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.3.2/src/lib.rs:128
       2: num_rational::Ratio<T>::new
                 at /Users/chadoh/.cargo/registry/src/github.com-1ecc6299db9ec823/num-rational-0.3.2/src/lib.rs:101
       3: <near_primitives_core::profile::ProfileData as core::fmt::Debug>::fmt
                 at /Users/chadoh/.cargo/registry/src/github.com-1ecc6299db9ec823/near-primitives-core-0.4.0/src/profile.rs:151
       4: core::fmt::run
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1116
       5: core::fmt::write
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1091
       6: std::io::Write::write_fmt
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
       7: <std::io::stdio::Stdout as std::io::Write>::write_fmt
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/stdio.rs:606
       8: std::io::stdio::print_to::{{closure}}
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/stdio.rs:890
       9: std::thread::local::LocalKey<T>::try_with
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/thread/local.rs:265
      10: std::io::stdio::print_to
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/stdio.rs:879
      11: std::io::stdio::_print
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/stdio.rs:907
      12: sim::with_macros::simulate_transfer_call_promise_panics_for_a_full_refund
                 at ./tests/sim/with_macros.rs:250
      13: sim::with_macros::simulate_transfer_call_promise_panics_for_a_full_refund::{{closure}}
                 at ./tests/sim/with_macros.rs:229
      14: core::ops::function::FnOnce::call_once
                 at /Users/chadoh/.rustup/toolchains/stable-2020-10-08-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227
      15: core::ops::function::FnOnce::call_once
                 at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
    note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

    test with_macros::simulate_transfer_call_promise_panics_for_a_full_refund ... FAILED

### CODE REVIEW

**Comment by chadoh** [comment]
@willemneal is this something you can look into?

**Comment by willemneal** [comment]
It corresponds to this line:

```rust
        writeln!(
            f,
            "Host gas: {} [{}% total]",
            host_gas,
         >  Ratio::new(host_gas * 100, all_gas).to_integer()
        )?;
```

This means that `all_gas` is zero.

**Comment by chadoh** [comment]
Where is that line?

**Comment by acuarica** [comment]
I'm having this exact same behaviour. Using last version. It would be great to be able to see the profile data.

**Comment by austinabell** [comment]
I just looked into this, the panic which occurs in this example is fixed but we are waiting on a release of an internal crate, I opened a PR to fix a potential panic (https://github.com/near/nearcore/pull/4599) and this fix will come in before the 4.0 stabilization. Sorry for the delay!

**Comment by austinabell** [comment]
Should be fixed with #639, going to close to tie with this

**Comment by zcstarr** [comment]
Thanks this will be awesome!

**Comment by austinabell** [comment]
Or actually, I misspoke, #639 cannot update the versions of nearcore for sim tests. Going to re-open, but I'm not certain this can be fixed before sim tests are deprecated altogether.

**Comment by austinabell** [comment]
Sim tests are being deprecated, there is no path to fixing this for us unfortunately :( sorry

**Pull request closed without merging**
