### PR TITLE
Add a simple log to examples for better devx

### PR DESCRIPTION
**Pull request by janedegtiareva**

### CODE REVIEW

**Comment by janedegtiareva** [comment]
It looks like error messages are usually done by e.g.  env::panic(b"Not enough allowance");
Do we want to switch that to log?

**Comment by nearmax** [comment]
> It looks like error messages are usually done by e.g. env::panic(b"Not enough allowance");
> Do we want to switch that to log?

I made a type. What I meant is:

> Let's have some meaningful log message, that reflects what is happening at the given moment of time.

**Comment by janedegtiareva** [comment]
> > It looks like error messages are usually done by e.g. env::panic(b"Not enough allowance");
> > Do we want to switch that to log?
> 
> I made a type. What I meant is:
> 
> > Let's have some meaningful log message, that reflects what is happening at the given moment of time.
Are you thinking something generic like "so and so fn got called" (see latest commit for example), or more specific to the individual examples?

**Comment by evgenykuzyakov** [comment]
@janedegtiareva Is it still needed?

**Comment by evgenykuzyakov** [comment]
Closing for now

**Pull request closed without merging**
