### PR TITLE
fix(contract-standards): required minimum gas is more than needed in `*_transfer_call()`

### PR DESCRIPTION
**Pull request by think-in-universe**
In `ft_transfer_call()` function implemented in the FT standard,

because here `GAS_FOR_FT_TRANSFER_CALL` already includes `GAS_FOR_RESOLVE_TRANSFER`, no need to count in `GAS_FOR_FT_TRANSFER_CALL` twice in `require!()`

https://github.com/near/near-sdk-rs/blob/2d7fc59c5450dfa301fa26de1c33a6ceb69408f9/near-contract-standards/src/fungible_token/core_impl.rs#L13

The same also happens to `nft_transfer_call()` in NFT standard,

`GAS_FOR_NFT_TRANSFER_CALL` already includes `GAS_FOR_RESOLVE_TRANSFER`

https://github.com/near/near-sdk-rs/blob/8b4f0d6779906b0a7947f75218a3b277b64e5e68/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L19

Though we also need to consider the required gas for `ft_on_transfer()` and `nft_on_transfer()`, we'd better add another constant for that if needed.

### CODE REVIEW

**Comment by itegulov** [comment]
Just realized that I don't know the purpose of these explicit gas checks. Is the idea just not to waste caller's gas when we know there is not enough?

> Though we also need to consider the required gas for ft_on_transfer() and nft_on_transfer(), we'd better add another constant for that if needed.

Well, those can be implemented in an arbitrary way by a user's contract, no? So we cannot know how much gas they would require.

**Comment by think-in-universe** [comment]
> Just realized that I don't know the purpose of these explicit gas checks. Is the idea just not to waste caller's gas when we know there is not enough?

yeah. that's part of the reason. also, we'd like to attach enough gas, so ensure `*_resolve_transfer()` is executed anyway. 

> Well, those can be implemented in an arbitrary way by a user's contract, no? So we cannot know how much gas they would require.

right. we cannot predict the gas cost of the token receiver. so maybe we just don't count in the  `*_on_transfer()` and only require the minimum gas. Then let developers to decide the total attached gas in their frontend code.

**Comment by itegulov** [comment]
> yeah. that's part of the reason. also, we'd like to attach enough gas, so ensure *_resolve_transfer() is executed anyway.

Be aware that there is still not guarantee that the async calls will happen, especially if you have a big payload. See https://github.com/near/near-sdk-rs/issues/619. But I am also not sure why you would want to be sure that `ft_resolve_transfer()` is always executed (@austinabell gave a good explanation [here](https://github.com/near/near-sdk-rs/issues/619#issuecomment-1080733095)). Do you have a specific use case in mind?

**Review by itegulov — APPROVED** [review]
The changes make sense to me, but you will still need another approval from @austinabell or @ChaoticTempest

**Review by austinabell — APPROVED** [review]
yes, this naming is also very confusing, because `GAS_FOR_FT_TRANSFER_CALL` includes gas for `RESOLVE_TRANSFER`, which is misleading.

**Pull request merged**
