### PR TITLE
fix CI tests

### LINKED ISSUE #196: Master branch CI failure
CI jobs with `NEAR_RELEASE=false` fail: https://travis-ci.com/github/near/near-sdk-rs/builds/174852125

@evgenykuzyakov Do you have any idea on how this can be resolved?

### PR DESCRIPTION
**Pull request by bowenwang1996**
fixes #196

### CODE REVIEW

**Comment by bowenwang1996** [comment]
@chefsale @ailisp I am getting compilation errors on CI due to ` the `wasm32-unknown-unknown` target may not be installed`. Is CI environment set up properly?

**Comment by ailisp** [comment]
It might not installed for stable rust. I just add it and rebuild

**Comment by nearmax** [comment]
Thank you!

**Comment by frol** [comment]
Does this mean that we might have broken the existing contracts since they got more expensive?

**Comment by bowenwang1996** [comment]
@frol yes it's possible, although I don't think it's breaking in most cases unless you wrote a function that no matter what the input is, it always consumes a lot of gas.

**Pull request merged**
