### PR TITLE
setup build image for contract builder

### PR DESCRIPTION
**Pull request by ilyar**
example result https://github.com/ilyar/near-sdk-rs/pkgs/container/near-sdk-rs%2Fnear-contract-builder

### CODE REVIEW

**Comment by austinabell** [comment]
I'll leave it to others to approve if this is helpful, as it's unclear how exactly this helps. By the way, there is an image set up already which is used in this repo (https://hub.docker.com/r/nearprotocol/contract-builder) not sure if it was not visible. 

Not sure in the value in having this connected to CI as this never really changes and we might want the control.

**Comment by ilyar** [comment]
@austinabell I didn't know that this already existed, I can't even imagine that you are using manual or private deployment processes

**Comment by austinabell** [comment]
> @austinabell I didn't know that this already existed, I can't even imagine that you are using manual or private deployment processes

I haven't touched any of the docker setup other than using the image, but @chefsale input on this would be appreciated.

**Comment by ilyar** [comment]
I see https://github.com/near/near-sdk-rs/tree/master/contract-builder and https://github.com/skyward-finance/contracts/blob/master/build_all.sh

but it should be something like this https://gist.github.com/ilyar/6d4fa5afd432532bd5170dc4de40e92c

**Comment by austinabell** [comment]
@rtsai123 @anshal-savla relevant discussion to updating the docker image. Something to consider

**Comment by austinabell** [comment]
#751

**Pull request closed without merging**
