### PR TITLE
fix: Increase GAS for NFT transfer call

### PR DESCRIPTION
**Pull request by danielwpz**
current value is too low to even run in testnet

### CODE REVIEW

**Comment by think-in-universe** [comment]
the related issue is #559

**Comment by danielwpz** [comment]
@mikedotexe please help review this as well

**Comment by mikedotexe** [comment]
Thanks @danielwpz seems like there is more discussion happening in #593 do you want to keep this issue? I've approved the other one and moved it into the "Awaiting Review" column for Dev Platform

**Comment by danielwpz** [comment]
@mikedotexe hi mike, this one and #593 are very similar, I think both places need to be updated

**Comment by danielwpz** [comment]
sure! will do @mikedotexe

**Comment by mikedotexe** [comment]
@danielwpz does my comment in the other issue make sense? Do you think this is still valid to keep open?

**Comment by austinabell** [comment]
Closing just because this is a stop-gap solution and we should soon come up with a better pattern for these.

cc @jlogelin input on this and the discussion on #593 would be appreciated to spark this issue again, as it's a real problem

**Pull request closed without merging**
